title: GUDMAP/RBK
email: your-email@example.com
description: >-
 This is the home of public documentation for the GUDMAP/RBK Consortiums.
baseurl: "/gudmap-rbk" # the subpath of your site, e.g. /blog
url: "https://ghastvhenry.github.io/" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
theme: jekyll-theme-leap-day

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
